## Homework 3

<!--
You can use the example3.Rmd or other files to find examples
of the codes you'll need to use to complete this assignment. I strongly
urge you to copy and paste relevant code that you know works from my
examples or instructions and then edit that code so you're working
with the appropriate variables for the homework.
-->

<!--
Set the working directory.
No Rchunk is needed to accomplish this.
-->

<!--
Read in the homework3.csv data. For each of the following steps you
should preface your R commands with some plain English explanation.
-->

Code to read in the data for the homework 3 assignment.

dat<-read.csv("homework3.csv")

<!--
Check the structure of the data.
-->
Code to check the structure of the data for the homework 3 assignment.

str(dat)

<!--
Find the mean, median, and standard deviation using the sd() function
for the overall level of conservatism.
-->

Code to find the mean, median and standard deviation for conservatism.

mean(dat$conservatism)
median(dat$conservatism)
sd(dat$conservatism)

From the above data we can see that the mean for conservatism is 52.3, the median is 53.8, and the standard deviation is 19.8

<!--
Find the mean level of support for freshmen only.
-->

Code to find the mean level of conservatism for only the freshmen.

mean(dat$conservatism[dat$year=="freshman"])

From this data we can see that the mean conservatism for freshman is 47.5

<!--
Find the mean level of support for male business students only.
-->

Code to find the mean level of conservatism for the sophomore business students.

mean(dat$conservatism[dat$year=="sophomore" & dat$major=="business"])

From this data set we can see that the mean conservatism for sophomore business students is 61.6

